---
output: 
  md_document:
    variant: markdown_github
---

## Trabajo individual para la asignatura "Big Data"

<!-- El párrafo de abajo has de dejarlo tal cual. NO HAS DE CAMBIAR NADA!!-->


Repo utilizado para elaborar el trabajo para la asignatura "Programación y manejo de datos en la era del Big Data" de la Universitat de València durante el curso 2022-2023. La página web de la asignatura puede verse aquí: <https://perezp44.github.io/intro-ds-22-23-web/>.


<!-- En la linea de abajo TIENES QUE SUSTITUIR "perezp44" por tu usuario de Github-->
La versión final del trabajo puede visualizarse en: <https://gomezz01.github.io/trabajo_BigData/>. 


<!-- Abajo podéis escribir lo que queráis, igual un resumen del trabajo, o ..., o ... pero al menos, creo que tienes que poner el título del trabajo y posiblemente tu nombre. Algo que explique porque está el repo en Github-->

# 2005 y 2006. Las dos del Nano

Mi nombre es Josep Gómez, y soy alumno de cuarto de economía de la Universitat de València. En la asignatura de Programación y manejo de datos en la era del Big Data hacemos un trabajo individual para ser avaluados. Este es el mío.
El título del trabajo es: 2005 y 2006, las dos del Nano. Haremos un pequeño viaje en el tiempo hacia los mejores años para el automobilismo español en la categoría reina para ver como hizo Fernando Alonso para llevarse al bolsillo dos títulos mundiales seguidos.


<!-- Finalmente, ACÚERDATE de que cuando hayas hecho los cambios y hayas dejado este archivo como te guste más, TIENES que knittearlo para que los cambios se actualicen en el fichero Readme.md, que es el que finalmente se visualizará en Github. El fichero Readme.md no has de editarlo a mano, sale de knittear Readme.Rmd-->

